name: emoclass
channels:
  - conda-forge
  - anaconda
dependencies:
  - gcc=8
  - cudatoolkit=11.1
  - cudnn
  - python=3.8
  - sox=14.4.2
  - tensorflow=2.7.0
  - tensorflow-gpu=2.7.0
  - pip
  - pip:
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - torch==1.8.0+cu111
    - torchaudio==0.8.0
    - sklearn
    - cython==0.29.12 
    - librosa==0.8.0 
    - numba==0.48 
    - unidecode 
    - inflect 
    - tensorboard 
    - matplotlib 
    - wandb 
    - future
    - packaging
    - sox==1.4.1
    - tqdm==4.60.0

