name: emoclass
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - cudatoolkit=11.1
  - python=3.8
  - pytorch-gpu=1.8.0 
  - torchaudio=0.8.0
  - sox=14.4.2
  - cudnn
  - tensorflow=2.7.0
  - tensorflow-gpu=2.7.0
  - pip:
    - sklearn
    - cython==0.29.12 
    - librosa==0.8.0 
    - numba==0.48 
    - unidecode 
    - inflect 
    - tensorboard 
    - matplotlib 
    - wandb 
    - future
    - packaging
    - sox==1.4.1
    - tqdm==4.60.0

